require("mylua.clipboard")
require("mylua.launchAlacrittyHere")

hs.hotkey.bind({ "option", "shift" }, "L", function()
	hs.alert("Logseq...")
	hs.application.launchOrFocus("Logseq")
end)
hs.hotkey.bind({ "option", "shift" }, "C", function()
	hs.alert("Code...")
	hs.application.launchOrFocus("Code")
end)
hs.hotkey.bind({ "option", "shift" }, "F", function()
	hs.alert("FireFox...")
	hs.application.launchOrFocus("FireFox")
end)
hs.hotkey.bind({ "option", "shift" }, "E", function()
	hs.alert("Finder...")
	hs.application.launchOrFocus("Finder")
end)
hs.hotkey.bind({ "option", "shift" }, "A", function()
	hs.alert("Alacritty...")
	hs.application.launchOrFocus("alacritty")
end)
hs.hotkey.bind({ "option", "shift" }, "K", function()
	hs.alert("Kitty...")
	hs.application.launchOrFocus("kitty")
end)

-- automatically reload config whenever init.lua changes
hs.loadSpoon("ReloadConfiguration")
spoon.ReloadConfiguration:start()
